# ?? Database ??????????????????????????????????????????????????????????????
JDBC_URL=jdbc:mysql://root:rIwknsJBnTsIQhtOjIQfHUVaXdIMgQqE@mysql.railway.internal:3306/railway
DB_USER=root
DB_PASSWORD=rIwknsJBnTsIQhtOjIQfHUVaXdIMgQqE

# ?? Mail (Gmail example ? replace with your credentials) ??????????????????
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=arpedjeyescomen@gmail.com
spring.mail.password=yetreqhhdbhkwzhs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ?? Server ????????????????????????????????????????????????????????????????
server.port=${PORT:8080}
