# ?? Database ??????????????????????????????????????????????????????????????
spring.datasource.url=mysql://root:rIwknsJBnTsIQhtOjIQfHUVaXdIMgQqE@mysql.railway.internal:3306/railway?allowPublicKeyRetrieval=true&useSSL=false&connectTimeout=60000&socketTimeout=60000&enabledTLSProtocols=TLSv1.2
spring.datasource.username=root
spring.datasource.password=rIwknsJBnTsIQhtOjIQfHUVaXdIMgQqE

# ?? Mail (Gmail example ? replace with your credentials) ??????????????????
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=arpedjeyescomen@gmail.com
spring.mail.password=yetreqhhdbhkwzhs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ?? Server ????????????????????????????????????????????????????????????????
server.port=8080
